version: "3.8"

services:
  # build: "/Users/tuanbui/Documents/2.Kobiton/kobiton-project/tuanbui-test/webpage/Dockerfile"
  #   context: .
  #   dockerfile: Dockerfile
  #   # name: webpage-demo-v3
  web:
    image: webpage-demo-v1:latest
    container_name: tuanbui-lab-docker-compose
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"